language: python

node_js:
  - "8"

python:
  - "2.7"
  - "3.6"

env:
  - DJANGO_SETTINGS_MODULE=helloworld.local_settings

install:
  - pip install -r requirements.txt
  - cd frontend
  - npm install

script:
  - npm run lint
